services:
    postgres:
        image: postgres:latest
        container_name: newsletter
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-newsletter}
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        command: postgres -N 1000
        volumes:
            - postgres_data:/var/lib/postgresql
volumes:
    postgres_data:
